name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Build Website
        run: npm run build
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::810453367775:role/test_role_to_acess_githubactions_tos3
          aws-region: us-east-1
          audience: sts.amazonaws.com
      - name: Copy to S3
        run: aws s3 sync ./build/. s3://test-cicd123
#1
